### ISSUE TITLE
Design a simpler UX

### ISSUE THREAD

**Issue by mike-audi** [tiki/apps-receipt-capacitor#186]
### Reason

The initial reward program has explicit criteria for receiving a payout

### Description

The managed reward program consists of a flat $1 per month for users who:
- link their gmail account
- link **1** other retailer account

The criteria for payout is:
- open the app once a week (to sync)
- keep both accounts linked for the entire month
- generate a minimum of 5 receipts

The UX should make this criteria clear and show users where they are against meeting it (in addition to the standard requirements of clearly stating what data is collected and how it will be used).

### Success Criteria

- [x] approved wireframes
- [x] explain clearly to the user the data requirements
- [x] explain clearly to the user the criteria for payout
- [ ] mockups that the engineering team can use to scope and build the changes

**Comment by timoguin** [comment]
Here's my first pass at sketching out the following 5 screens:

- Consent Screen
- Main Screen
- Linked Accounts Screen
- Link Account Screen
- Offer Detail Screen

# Screens 1-3

On the Consent Screen, I removed the copy about how data is used. I think that should be additional copy that can be navigated to by clicking on the question mark logo.

On the Main Screen, the "Link Gmail" and "Link Retailer Account" sections should be clickable and take the user to the Link Account screen. Completed actions should be de-emphasized and moved to the bottom of the list (or removed from this view). The requirements that are incomplete should be at the top. The question mark should navigate to the Offer Detail Screen.

![CCI09212023](https://github.com/tiki/apps-receipt-capacitor/assets/671968/e5f4c8cb-d248-4876-b51a-c6d94343e172)

# Screens 4-5

The offer detail screen should show a collection of logos: Gmail and a few select (popular) retailers.

It will require additional copy that allows the user to view all the supported merchants when they click for more detail. That may require another screen. We can give them highlights with a limited list of logos.

![CCI09212023_0001](https://github.com/tiki/apps-receipt-capacitor/assets/671968/622aff80-ad3e-4192-8b82-45828e4226f6)

**Comment by mike-audi** [comment]
@timoguin @sfaria27 incomplete, but this is the first set of screens for the main page

![image](https://github.com/tiki/apps-receipt-capacitor/assets/3769672/d698f10f-b377-4d4d-adc8-69098e68ba06)

**Comment by mike-audi** [comment]
![image](https://github.com/tiki/apps-receipt-capacitor/assets/3769672/ccf47d63-5bf5-483e-afba-96480532bd14)

![image](https://github.com/tiki/apps-receipt-capacitor/assets/3769672/d0888da9-0b00-4578-ba4d-31a568a6a605)

![image](https://github.com/tiki/apps-receipt-capacitor/assets/3769672/cecc8ddd-ed9d-4e87-a8fe-d547a76ed1e9)


Notes:
- If the user does not have an account connected, skip the account list screen and take them straight to the connect form when they click the Gmail or Retailer button.
- Only show the Sign in with Google option and divider if OAuth is enabled.
- Retailer Icon in dropdown is optional if it's hard to do.
- Only show the remove warning screen if the user is removing their last remaining Gmail or Retailer account.

**Comment by mike-audi** [comment]
![image](https://github.com/tiki/apps-receipt-capacitor/assets/3769672/a270d4ed-0fdf-4a87-a000-2a399d268b78)

Notes:
- I need help figuring out a better graphic with more "pop"
- I think with a better graphic, I can cut down the words in the description to something like "We're testing out a new program —cash for receipts!"

**Comment by sfaria27** [comment]
https://www.figma.com/file/1cY8mJvJ3QBKXiCsSZvXqt/Reward-Graphics?type=design&node-id=307-4&mode=design&t=0Zg5V8i0R0EqE5O6-0 this is the stuff i did for the shopify example. could be similar to that with like dollar bills replacing the discount image

- could also have like a receipt img with a key over it and an unlocked chest or something with some cash in it.
- probably harder to make but kind of funny is a "receipt register" that prints out dollar bills. this program is basically just an inverse cash register lol
- could show a basic linking flow like a gmail icon, a little collage of a few major retailers, and a collage of a few receipts with arrow to a $1 img or a dollar bill img
- could show a collage of receipts with a fade out toward the center and a big bold $1 sign or bill in the center
- could literally show the reward screen progress example with the criteria met & cash out button (the actual mobile interface they'd see and use)
- could be a simplified version of above

**Comment by mike-audi** [comment]
[ReceiptFlow.pdf](https://github.com/tiki/apps-receipt-capacitor/files/12704975/ReceiptFlow.pdf)
