### ISSUE TITLE
Gmail IMAP login error

### ISSUE THREAD

**Issue by ricardobrg** [tiki/apps-receipt-capacitor#192]
### Reason

It is not possible to login with Gmail IMAP currently

### Description

The login flow for Gmail IMAP redirects the user to a webview to create Gmail app password. After the app pasword creation, the UI does not close and the user gets stuck.

It is a known issue for Microblink and they are working in a fix

### Success Criteria

- [ ] After the app password creation, the user is redirected to the app UI, closing Gmail UI.

**Comment by ricardobrg** [comment]
Microblink updated the SDK but the error is not fixed yet.

Their feedback on iOS: 
 • Are you able to reproduce this issue using our Beta app on iOS by any chance? https://testflight.apple.com/join/3oGcYulN
 • Otherwise, on iOS you can enable the debug mode for e-receipts by setting the NSUserDefault br_ereceipt_debug to TRUE prior to invoking any methods or properties on our SDKs. This should give you some logging in the console when connected to XCode, and may provide more details on the issue (I wasn't able to reproduce). This will also send additional logs our way
 @JesseMonteiro could you please test this?
 
On Android:
I think an issue may remain. we're investigating now.

**Comment by ricardobrg** [comment]
removing [iOS] from title since it affects both.

**Comment by ricardobrg** [comment]
@mike-audi @timoguin could you please with your gmail in Microblink testflight too? Just to confirm that the error is not because our account is non-US.

**Comment by JesseMonteiro** [comment]
I try with the TestFlight Microblink app and i had the same problem
https://github.com/tiki/apps-receipt-capacitor/assets/8730443/e6e351eb-b51f-4fdb-ae48-e8a8a5aa33cb

**Comment by ricardobrg** [comment]
Spliting this into 2 new issues
tiki/capture-receipt-capacitor#288
tiki/capture-receipt-capacitor#289
