### ISSUE TITLE
Update copy and design for Learn More screen

### ISSUE THREAD

**Issue by timoguin** [tiki/apps-receipt-capacitor#219]
### Reason

New user requirements for the rewards pilot need to be detailed

### Description

The Learn More (offer detail) screen needs to detail the new requirements for users to receive payouts, including listing out all the supported retailers / merchants.

This is where we need to expound on anything that can't reasonably fit on the other screens.

### Success Criteria

- [x] Design new layout based on wireframes (see references)
- [x] Compile full list of supported merchants for account linking
- [x] Compile full list of supported merchants for email linking
- [x] Acquire icons to use for retailers
- [x] Write new copy
- [x] New screen / page fully implemented in example app

### Additional Information

- https://github.com/tiki/apps-receipt-capacitor/issues/186#issuecomment-1728963476
- Supported for account linking: https://ereceipts.blinkreceipt.com/account-linking
- Supported for email linking: https://ereceipts.blinkreceipt.com/us
- Markdown source: https://github.com/tiki/apps-receipt-capacitor/blob/main/src/assets/learn-more.md
- Vue source: https://github.com/tiki/apps-receipt-capacitor/blob/main/src/components/learn-sheet.vue

**Comment by sfaria27** [comment]
[Learn more.docx](https://github.com/tiki/apps-receipt-capacitor/files/12742419/Learn.more.docx)

Review req'd @timoguin. Initial draft
