### ISSUE TITLE
[UI] User should not add multiple accounts from the same retailer

### ISSUE THREAD

**Issue by ricardobrg** [tiki/apps-receipt-capacitor#233]
### Reason

Microblink SDK just let one account per retailer.

### Description

The UI let user add multiple accounts for the same retailer. It should not be allowed because the Microblink SDK just handles on account at a time per retailer. If the user can add more than one from the same retailer in the UI, it would be confusing.

### Success Criteria

- [x] Define the UX for that 
- [ ] Implement the defined UX 
- [ ] user should not be able to add multiple accounts from the same retailer

**Comment by timoguin** [comment]
As discussed in Discord, let's make the dropdown dynamic and simply remove retailers that are already linked. This will prevent the user from trying to add a duplicate retailer account without us having to design a warning / error dialog.
