### ISSUE TITLE
[UI] Fix Email Overflow

### ISSUE THREAD

**Issue by JesseMonteiro** [tiki/apps-receipt-capacitor#309]
### Reason

The large email hide the remove buttom

### Description

![IMG_9759](https://github.com/tiki/apps-receipt-capacitor/assets/8730443/310c27a5-b62c-47d1-957e-91d4420c3b0d)
![IMG_9760](https://github.com/tiki/apps-receipt-capacitor/assets/8730443/46bd237c-bd40-46d0-91c2-20bff0287f59)

### Success Criteria

- [ ] Fit the email and show the remove buttom

**Comment by ricardobrg** [comment]
outdated
