### ISSUE TITLE
[iOS] Cannot login in a previously failed IMAP login

### ISSUE THREAD

**Issue by JesseMonteiro** [tiki/apps-receipt-capacitor#311]
### Reason

When we login and fail, we cant logout and login again

### Description

If we had a login problem with account, we setup the imap account and don't login we cant logout because don't show in accounts list and if we try login again, they say duplicated email. So we need to put the solution already made in main code to release.

### Success Criteria

- [ ] Update de code to treat IMAP error login

**Comment by ricardobrg** [comment]
@JesseMonteiro is this still happening?

**Comment by MiroBenicio** [comment]
close as outdated
