### ISSUE TITLE
[iOS] ScanResult error RetailerId invalid on Email Scan

### ISSUE THREAD

**Issue by JesseMonteiro** [tiki/apps-receipt-capacitor#312]
### Reason

The scan don't receive my scan

### Description

We a try scan my receipts a had for microblink one receive but after send to capacitor the type script reject my recepit with the message "invalid retailerId"

### Success Criteria

- [ ] Receive all scans

**Comment by ricardobrg** [comment]
@JesseMonteiro is this still happening?
