### ISSUE TITLE
Initial Scoping of Kard API Integration

### ISSUE THREAD

**Issue by sfaria27** [tiki/apps-receipt-capacitor#330]
As a development team, we recognize the importance of thoroughly scoping the integration of the Kard API with our Cashback Connections application. This initial scoping phase is crucial to gain a deep understanding of the technical components and requirements for seamless integration. The key objectives of this story include:

- **Identify Integration Points:** We will identify the specific integration points where the Kard API will be incorporated into our application. This includes user registration, card linking, merchant discovery, and cashback rewards redemption.

- **Define Data Flow:** A comprehensive understanding of the data flow between our application and the Kard API is essential. We will outline the data exchange mechanisms, formats, and protocols to ensure efficient communication.

- **Technical Challenges:** During the scoping process, we will proactively identify potential technical challenges or complexities that may arise during integration. This includes any unique features or constraints of the Kard API.

- **Resource Allocation:** We will determine the development resources required for the integration, including developers, testing, and quality assurance.

- **Timeline and Milestones:** Based on the scoping results, we will establish a clear timeline and milestones for the integration process. This will enable effective project management and coordination.

By completing this initial scoping, we aim to set a strong foundation for a successful and efficient integration of the Kard API into the Cashback Connections application, ensuring a smooth and value-driven user experience.

**Comment by ricardobrg** [comment]
Adding the docs from the other issue https://developer.getkard.com/

**Comment by ricardobrg** [comment]
UI scoping https://github.com/tiki/apps-receipt-capacitor/issues/341

**Comment by mike-audi** [comment]
API spec coming soon.

Notes:
- Kard uses client credentials for oauth, so all transactions need to be proxied thru a tiki backend service.
- We will need the following endpoints
  - earnings (lifetime and month to date)
  - offers (sorted and filtered for the user)
  - estimate (calculate based on past txn, offers, and linked accounts)
  - register user (user id + app id, requires us to roll out account service v3)
