### ISSUE TITLE
Bottom sheet is closing wrongly

### ISSUE THREAD

**Issue by MiroBenicio** [tiki/apps-receipt-capacitor#342]
### Reason

the bottom sheet is closing while the user touch close to the learn more button in the offer sheet

### Description

The bottom sheet is closing wrongly while the user touchs nearby the the learn more button in the offer sheet

### Success Criteria

- [ ] the behavior descripted should not happen

### Additional Information

Problably the swipe function is closing the bottom sheet, because the div classname of the learn more button also is "title"

**Comment by ricardobrg** [comment]
outdated
