### ISSUE TITLE
Compile Backend Components Documentation

### ISSUE THREAD

**Issue by sfaria27** [tiki/apps-receipt-capacitor#442]
As a team member, I need to compile documentation on the backend components of the receipt scanning feature for the high-level system overview. This documentation will offer insights into the architecture and functionality of the backend system.

## Acceptance Criteria
- Identify and list all backend components involved in the receipt scanning feature.
- Document the role and responsibilities of each backend component.
- Specify any dependencies between backend components.
- Include information on data storage, processing, and retrieval mechanisms.
- Ensure the documentation is well-organized and easily accessible.

**Comment by ricardobrg** [comment]
### What Happens Behind the Scenes When a Receipt is Submitted?

1. **Verify Publisher Identity and Data Integrity**

    - **What:** We check the identity of the publisher and ensure that the data hasn't been tampered with.
    
    - **How:** The publisher's identity is verified using the JWT (JSON Web Token) sent with the request. This ensures that the request originated from the publisher and hasn't been altered in transit.
    
    - **Systems Involved:** TIKI Data Provider API

2. **Check User's License**

    - **What:** We verify if the user has a valid license.
    
    - **How:** TIKI License API is called to check the validity of the user's license. If there is no license or it has expired, the request is rejected.
    
    - **Systems Involved:** TIKI License API, TIKI Data Provider API

3. **Create a Request Record**

    - **What:** We generate a unique ID for the request for future reference.
    
    - **How:** An ID for the request is created, and an HTTP response is sent back with this ID.
    
    - **Systems Involved:** TIKI Data Provider API

4. **Extract Text from the Image**

    - **What:** We use Amazon Textract, a service by AWS, to extract text from the image.
    
    - **How:** The image is sent to Amazon Textract, which returns the text. The image is retained in ephemeral memory only until it's sent for text extraction.
    
    - **Systems Involved:** Amazon Textract, TIKI Data Provider API

5. **Convert Text to Receipt Data**

    - **What:** We convert the extracted text into structured Receipt Data for ingestion into TIKI Ocean.
    
    - **How:** The text is converted into receipt data. The text is retained in ephemeral memory only until the conversion is complete, after which it's discarded.
    
    - **Systems Involved:** TIKI Data Provider API

6. **Publish Receipt Data to TIKI Ocean**

    - **What:** The Receipt data is sent to TIKI Ocean. The request record created in step 3 is updated.
    
    - **How:** The Receipt data is transmitted to TIKI Ocean, and the request record is updated.
    
    - **Systems Involved:** TIKI Data Provider API, TIKI Ocean
