### ISSUE TITLE
Create SDK Documentation

### ISSUE THREAD

**Issue by sfaria27** [tiki/apps-receipt-capacitor#443]
As a team member, I need to create straightforward documentation for the SDK, covering scanning, authentication, and licensing. The documentation should be easily understandable for developers integrating the SDK into their applications.

**Comment by ricardobrg** [comment]
# TIKI Data Provider Client Library (Capacitor + Vue.js)

The TIKI Data Provider API is based on HTTP, making it compatible with any standard HTTP client for sending requests and processing responses.

However, the TIKI Data Provider Client Library goes a step further by providing enhanced Capacitor integration, pre-built UIs, improved security measures, and support for calls requiring user authorization. By leveraging this library, you can eliminate the necessity of manually configuring HTTP requests and parsing responses.

## Installation

#### With Vue >=3.0.0
```shell
npm i @mytiki/data-provider
```

#### With Vue 2.7.14
```shell
npm i @mytiki/data-provider-vue2
```

Next, if you don't already have a `publishingId` from TIKI, **create a free account** and make a project at [console.mytiki.com](https://console.mytiki.com).

## Getting Started

1. Register the plugin with your Vue app

#### With Vue >=3.0.0

```ts
import { createApp } from "vue";
import App from "@/app.vue";

import Tiki from "@mytiki/data-provider";

createApp(App)
    .use(Tiki, {
      company: {
        name: "Company Inc.",
        jurisdiction: "Tennessee, USA",
        privacy: "https://your-co.com/privacy",
        terms: "https://your-co.com/terms",
      },
      publishingId: "YOUR TIKI PUBLISHING ID",
    }) 
    .mount("#app");
```

#### With Vue 2.7.15

```ts
import Vue from "vue";
import App from "./app.vue";

import Tiki from "@mytiki/data-provider-vue2";

Vue.use(Tiki, {
  company: {
    name: "Company Inc.",
    jurisdiction: "Tennessee, USA",
    privacy: "https://your-co.com/privacy",
    terms: "https://your-co.com/terms",
  },
  publishingId: "YOUR TIKI PUBLISHING ID",
});

new Vue({ render: (h) => h(App) }).$mount("#app");
```

_This registers the Vue Component as `TikiReceipt` and provides the service `TikiService` as an injectable object name `Tiki`._

2. Add the stylesheet for the component to your primary stylesheet (e.g. `main.css`)

#### With Vue >=3.0.0

```css
@import "@mytiki/data-provider/dist/data-provider.css";
```

#### With Vue 2.7.15

```css
@import "@mytiki/data-provider-vue2/dist/data-provider.css";
```

### Initialization
To initialize just inject the `TikiService` and pass in your systems unique identifier for the user. If you use emails (you shouldn't 😝), we recommend hashing it first.

#### With Vue >=3.0.0

```vue
<script setup lang="ts">
  import { inject } from "vue";
  import { type TikiService } from "@mytiki/data-provider";
  
  const tiki: TikiService | undefined = inject("Tiki");
  tiki?.initialize(id).then(() => console.log("Tiki Initialized"));
</script>
```

#### With Vue 2.7.15

```vue
<script setup lang="ts">
  import { inject } from "vue";
  import { type TikiService } from "@mytiki/data-provider-vue2";
  
  const tiki: TikiService | undefined = inject("Tiki");
  tiki?.initialize(id).then(() => console.log("Tiki Initialized"));
</script>
```

### Receipt Scanning
Utilize the `TikiService.scan()` method to initiate the scanning of a receipt. This method returns a Promise containing the receipt ID, which can be employed to monitor the progress of receipt parsing through the API.

```typescript
const receiptId = await TikiService.scan();
```

Before initiating the receipt scan, the `/licenses` API endpoint is invoked to validate the user's license. In case of an invalid license, the user is prompted to accept the license terms before gaining access to the camera for scanning.

The [Capacitor camera plugin](https://capacitorjs.com/docs/apis/camera) is employed to open the camera and capture images for receipt scanning. Users have the flexibility to capture multiple images for scanning lengthy receipts. These images are temporarily stored in memory and later combined before the upload process.

Upon completion of the image capture, the resulting image is uploaded to the `/receipts` endpoint. The endpoint responds with the receipt ID, enabling users to track the progress of the receipt parsing.

### Monitoring Receipt Parsing Progress
To check the parsing progress of a receipt, utilize the `TikiService.progress(receiptId)` method. This method calls the `/receipts` endpoint passing a `receiptId` which returns one of the following statuses: `PROCESSING`, `REJECTED`, or `PUBLISHED`.

```typescript
const status = await TikiService.progress(receiptId);
```
