### ISSUE TITLE
Compile Backend Components Documentation

### ISSUE THREAD

**Issue by sfaria27** [tiki/apps-receipt-capacitor#454]
As a team member, I need to compile documentation on the backend components of the CLO feature for the high-level system overview. This documentation will offer insights into the architecture and functionality of the backend system.

## Acceptance Criteria
- Identify and list all backend components involved in the CLO feature.
- Document the role and responsibilities of each backend component.
- Specify any dependencies between backend components.
- Include information on data storage, processing, and retrieval mechanisms.
- Ensure the documentation is well-organized and easily accessible.

**Comment by ricardobrg** [comment]
# CLO Features Process Documentation

## 1. Verify Data Provider Identity and Data Integrity

### What:
We ensure the authenticity of the data provider and verify the integrity of the submitted data.

### How:
- Data provider identity is verified using the JSON Web Token (JWT) received with the request.
- JWT is obtained from TIKI Auth and used for authentication with TIKI Data Provider API during receipt image upload.

### Systems Involved:
- Data provider requests JWT from TIKI Auth.
- TIKI Data Provider API authenticates using the JWT to verify identity.

## 2. Check User's License

### What:
We validate if the data provider possesses a valid license for the user data.

### How:
- TIKI Data Provider API checks license validity using the TIKI License API
- Requests without a valid license or expired licenses are rejected.

### Systems Involved:
- TIKI Data Provider API communicates with TIKI License API to verify the data provider's license.

## 3. Create a Request Record

### What:
We generate a unique ID for tracking and future reference.

### How:
- TIKI Data Provider API creates a unique request ID for each submission.
- An HTTP response includes this ID for user reference.

### Systems Involved:
- TIKI Data Provider API generates and returns the request ID.

## 4. Add a user Card

### What:
We send the user card informatio to [Kard](https://www.getkard.com/issuers) to source offers and assign rewards to the user.

### How:
- TIKI CLO Service authenticates with [Kard](https://www.getkard.com/issuers) using its internal credentials.
- The user is identified by the TIKI's internal user id and the card information is sent with no cardholder PII. A sample of the sent data can be found in [Kard docs](https://developer.getkard.com/#operation/postUserCard) 
- The card information is retained in ephemeral memory until the card is registered with Kard, then discarded.

### Systems Involved:
- TIKI CLO Service authenticates with [Kard](https://www.getkard.com/issuers) using its internal credentials.
- Kard does not require any cardholder information. The card data is treated according to their [Privacy Policy](https://www.getkard.com/privacypolicy)

## 5. Send transaction data

### What:
We send the transaction data to:
1. Kard to automatically identify redeemable card-linked offers (CLOs) for reward program cardholders.
2. TIKI Ocean to make it available to the data provider cleanroom and to be licensed to data buyers.

### How:
- TIKI CLO Service authenticates with [Kard](https://www.getkard.com/issuers) using its internal credentials.
- The user is identified by the TIKI's internal user id and the transaction information is sent with no cardholder PII. A sample of the sent data can be found [Kard docs](https://developer.getkard.com/#operation/incomingTransactionEndpoint)
- Tansaction data is structured to be ingested by TIKI Ocean.

### Systems Involved:
- TIKI CLO Service forwards transaction data to Kard and TIKI Ocean.
- Kard matches the redeemable CLO and return the reward.
- TIKI Ocean saves the transaction data into the data repository.
