### ISSUE TITLE
Compile SDK Documentation

### ISSUE THREAD

**Issue by sfaria27** [tiki/apps-receipt-capacitor#455]
As a team member, I need to create straightforward documentation for the SDK, covering scanning, authentication, and licensing. The documentation should be easily understandable for developers integrating the SDK into their applications.

**Comment by ricardobrg** [comment]
# TIKI CLO Client Library Documentation

The TIKI CLO Client Library is a convenient wrapper around the CLO APIs, simplifying integration with your application. It provides methods for common CLO functionalities such as managing user cards, transactions, and rewards. The library is designed to work as a Capacitor Plugin, making it easy to connect to the CLO APIs.

## Installation

To use the TIKI CLO Client Library, you need to install it as a dependency in your project. Add the following dependency to your project:

```bash
npm install @mytiki/apps-rewards
```

## Initialization

To initialize the library, inject the `TikiService` and pass in your system's unique identifier for the user.

### Authorization

The library handles authorization by automatically requesting a short-lived token using the customer's public Provider ID and User ID. It also includes logic for refreshing authorization tokens upon expiration.

#### With Vue >=3.0.0

```html
<script setup lang="ts">
  import { inject } from "vue";
  import { type TikiService } from "@mytiki/clo-client-library";
  
  const tiki: TikiService | undefined = inject("Tiki");
  tiki?.initialize(publishingId, userId).then(() => console.log("Tiki Initialized"));
</script>
```

#### With Vue 2.7.15

```html
<script setup lang="ts">
  import { inject } from "vue";
  import { type TikiService } from "@mytiki/clo-client-library";
  
  const tiki: TikiService | undefined = inject("Tiki");
  tiki?.initialize(publishingId, userId).then(() => console.log("Tiki Initialized"));
</script>
```

## User Cards

### Link a Card to a User

To link a card to a user, use the `cards.add` method. It requires the card details.

```typescript
const cardDetails = {
  bin: 123456,
  last4: 7890,
  issuer: "Name_Of_Issuer",
  network: "VISA"
};

tiki?.cards.add(cardDetails).then(response => {
  console.log(response);
});
```

### Get User Cards

To retrieve the list of linked cards for a user, use the `cards.get` method.

```typescript
tiki?.cards.get().then(response => {
  console.log(response);
});
```

## User Offers

### Get User Offers

To retrieve the list of available offers for a user, use the `offers.get`.

```typescript
tiki?.offers.get().then(response => {
  console.log(response);
});
```

## Transactions

### Send a Transaction

To send a transaction for matching with CLOs, use the `transaction` method. It requires the transaction details.

```typescript
const transactionDetails = {
  transactionId: "txn-789",
  amount: 1500,
  currency: "USD",
  status: "APPROVED",
  description: "Purchase at Some Merchant",
  merchantId: "some-merchant-id",
  cardBIN: 123456,
  cardLastFour: 7890
};

tiki?.transaction(transactionDetails).then(response => {
  console.log(response);
});
```

## User Rewards

### Get User Rewards

To retrieve the current user rewards, use the `rewards` method. It will return a `Rewards` object witht the current balance and a history of the rewards.

```typescript
tiki?.rewards().then(response => {
  console.log(response);
});
```

## Data Protection and Privacy

The Client Library maximizes user security using industry best practices for tokenized authorization and follows a minimum necessary data policy for privacy. It does not persist any user data, and all data sent to the CLO APIs is discarded upon upload. Transport security is ensured with HTTPS and TLS 1.3 for encryption.

For compliance review, the entire platform is open-source and available on [github.com/tiki](https://github.com/tiki). This Client Library can be found at [github.com/tiki/apps-receipt-capacitor](https://github.com/tiki/apps-receipt-capacitor).

### Data Persistence

The Client Library does not persist any user data. All user and cardholder data is sent directly to the CLO APIs, kept in-memory and discarded upon upload. Authorization tokens are stored in the local device's encrypted storage and only accessible to the application during runtime. 

### Cardholder information

No cardholder information is required at any time to handle the CLO features in Client Library or CLO APIs. The only data needed for matching the card with available offers is the last 4 digits of the card and the BIN, usually the first 4-6 digits. 

### Transport Security

All library requests to the CLO APIs utilize HTTPS with TLS 1.3 for transport encryption.
