### ISSUE TITLE
Document Data Flow

### ISSUE THREAD

**Issue by sfaria27** [tiki/apps-receipt-capacitor#456]
As a team member, I need to create a comprehensive document that outlines the flow of data from the initial scan of a receipt to the final sale. This document will serve as a reference for stakeholders, detailing each step in the process and the systems involved.

**Comment by ricardobrg** [comment]
### 1. **Submit user card and transactions:**
    - **What Happens:**
     - The data provider submits a user credit card information to activate the Card Linked Offers.
   - **Why:**
     - To identify the offers to which the user is elegible and link the transactions to reward the user. 
   - **Outcome:**
     - The Credit Card is sent to the TIKI CLO API with no cardholder PII. Only the last 4 digits, the BIN, the issuer and the network are required.
### 2. **Publisher Identity Verification and Data Integrity Check:**
   - **What Happens:**
     - We ensure the identity of the publisher who submitted the card information.
     - We check that the card or transaction data hasn't been tampered with during its journey to our system.
   - **Why:**
     - To confirm that the data comes from the publisher.
   - **Outcome:**
     - If the verification fails, the request is rejected.
     - If everything checks out, we move to the next step.

### 3. **User's License Check:**
   - **What Happens:**
     - We confirm whether the user has a valid license to submit its card and transaction data.
   - **Why:**
     - To ensure compliance with legal agreements and data usage policies.
   - **Outcome:**
     - If the user has a valid license, we proceed; otherwise, the request is rejected.

### 4. **Send card or transaction data to the CLO provider:**
   - **What Happens:**
     - We send the card and transactions data to Kard to provide the card linked offers from popular brands.
   - **Why:**
     - The card data is sent to Kard to identify the offers and rewards for a user.
     - The transaction data is sent to Kard to confirm the usage of the offer and redeem the reward.
   - **Outcome:**
     - Kard send specific offers for each user.
     - When a transaction is sent to Kard, it matches a eligible offer and send back the reward.

### 5. **Publish Transaction data to TIKI Ocean:**
   - **What Happens:**
     - The structured transaction data is sent to TIKI Ocean, our central data repository.
   - **Why:**
     - To store the transaction data securely and make it accessible for data buyers.
     - To reward the user when their transaction data is licensed.
   - **Outcome:**
     - The transaction data is successfully stored in TIKI Ocean.
     - When a licensor uses the transaction data, the user is rewarded.
