### ISSUE TITLE
Improve user experience with Gmail App Password

### ISSUE THREAD

**Issue by MiroBenicio** [tiki/apps-receipt-capacitor#62]
As a user 
I want helpful error messages
so that I understand how to conect my gmail account

### What it is now
The user receive a standard error message from google about the need to create an App Password to connect the gmail account

### What it should be
Before Gmail Login show the instructions for create an app password to the user

![image](https://github.com/tiki-bar/tiki-capture-receipt-capacitor/assets/96149507/465e705f-bac7-4bbe-8419-4471a1a1fa42)

**Comment by ricardobrg** [comment]
This is a known Microblink bug. They are working on it.
