### ISSUE TITLE
Improve the design for closing the UI with Swipe Movement

### ISSUE THREAD

**Issue by MiroBenicio** [tiki/apps-receipt-capacitor#67]
as a developer
I need to build a better design for close the UI

### What it is now
The function uses the className of the elements to detect the area of the touch event to close the UI

### What it should be
It needs to be a more secure way to do it, maybe using a specific element to press, hold and drag, so its close the UI.

### Tecnical details
Needs to use other css classes or figure out another way to do it.

### Acceptance criteria
A trusty design to the feature

#60 
Continues on this issue

#66 
Continues on this issue

**Comment by mike-audi** [comment]
closed by #289
